# 捕获异常

对异常进行处理，称为捕获异常。

```python
x = int(input('输入被除数: '))
y = int(input('输入除数: '))
print(x / y)
```

看起来没问题，如果除数是 0 呢：

<div class="run"></div>

```python
x = 10
y = 0
print(x / y)
```

程序抛出了异常，我们没有捕获它，这个异常的名字叫：

```
ZeroDivisionError
```

捕获异常:

<div class="run"></div>

```python
try:
    x = 10
    y = 0
    print(x / y)
except ZeroDivisionError:
    print("除数不能为0!")
```

## 内置的异常类

| 类名              | 描述                                                            |
| ----------------- | --------------------------------------------------------------- |
| Exception         | 几乎所有的异常类都是从它派生而来的                              |
| AttributeError    | 引用属性或给它赋值失败时引发                                    |
| OSError           | 操作系统不能执行指定的任务(如打开文件)时引发，有多个子类        |
| IndexError        | 使用序列中不存在的索引时引发，为 LookupError 的子类             |
| KeyError          | 使用映射中不存在的键时引发，为 LookupError 的子类               |
| NameError         | 找不到名称(变量)时引发                                          |
| SyntaxError       | 代码不正确时引发                                                |
| TypeError         | 将内置操作或函数用于类型不正确的对象时引发                      |
| ValueError        | 将内置操作或函数用于这样的对象时引发:其类型正确但包含的值不合适 |
| ZeroDivisionError | 在除法或求模运算的第二个参数为零时引发                          |

无需记忆这些类，遇到时查询文档即可。
